// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// GenFormMatchIsotopeMsMs_R
Rcpp::List GenFormMatchIsotopeMsMs_R(Rcpp::DataFrame ms, Nullable<Rcpp::DataFrame> msms, Rcpp::Nullable<double> m, Rcpp::Nullable<Rcpp::List> settings);
RcppExport SEXP _genform_GenFormMatchIsotopeMsMs_R(SEXP msSEXP, SEXP msmsSEXP, SEXP mSEXP, SEXP settingsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type ms(msSEXP);
    Rcpp::traits::input_parameter< Nullable<Rcpp::DataFrame> >::type msms(msmsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<double> >::type m(mSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type settings(settingsSEXP);
    rcpp_result_gen = Rcpp::wrap(GenFormMatchIsotopeMsMs_R(ms, msms, m, settings));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_genform_GenFormMatchIsotopeMsMs_R", (DL_FUNC) &_genform_GenFormMatchIsotopeMsMs_R, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_genform(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
