# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GenFormMatchIsotopeMsMs_R <- function(ms, msms = NULL, m = NULL, settings = NULL) {
    .Call('_genform_GenFormMatchIsotopeMsMs_R', PACKAGE = 'genform', ms, msms, m, settings)
}

